---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: fedora-wayblue
description: Fedora Wayblue Sway workstation

base-image: ghcr.io/wayblueorg/sway
image-version: latest

modules:
  - from-file: common-packages.yml
  - from-file: kubernetes.yml
  - from-file: flatpaks.yml
  - from-file: fonts.yml

  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - k3s.service

  - type: signing
